version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: training-coupon-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-password}
      MYSQL_DATABASE: training_coupon
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data-local:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: training-coupon-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data-local:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data-local:
  redis-data-local:

